apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: ei-z-backend
spec:
  params:
  - name: pathToContext
    value: /workspace/docker-source
  - name: targetNamespace
    value: ei-z-backend
  - name: domain
    value: 192.168.64.2.nip.io
  - name: subdomain
    value: z-backend
  pipelineRef:
    name: deploy-legacy
  resources:
  - name: source
    resourceRef:
      name: mesh-apic-demo-git
  - name: image
    resourceRef:
      name: myservice-image