apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apic-api-test
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/tags: cli
    tekton.dev/displayName: "apic cli"
spec:
  description: This task performs operations the test of publish API. 
  resources:
    inputs :
      - name: source
        type: git
  params:
    - name: server
      description: The APIC server endpoint
      type: string
    - name: org
      type: string
    - name: catalog
      type: string
    - name: consumer_org
      type: string
    - name: app 
      type: string
    - name: app_id
      type: string
  steps:
    - command:
        - /bin/bash
        - '-c'
        - apic login --accept-license --server $(params.server) --username $USERNAME --password $PASSWORD --realm $REALM
      image: 'jtarte/apic-cli:latest'
      name: login
      resources: {}
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: apic-creds
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: apic-creds
              key: password 
        - name: REALM
          valueFrom:
            secretKeyRef:
              name: apic-creds
              key: realm 
    - command:
        - /bin/bash
        - '-c'
        - cat /workspace/source/apic/subs-org.yaml | sed "s#TARGET_PRODUCT#$(apic products:list -s $(params.server) -o org1 -c sandbox --scope catalog cloudfrontendproduct | grep cloudfrontendproduct:1.0.0 | awk -F ' ' '{print $4}')#g" > /workspace/source/apic/subs.yaml
      image: 'jtarte/apic-cli:latest'
      name: prepare-api-subscription
      resources: {}
    - command:
        - /bin/bash
        - '-c'
        - apic subscriptions:create --server $(params.server) -o $(params.org) -c $(params.catalog) --consumer-org $(params.consumer_org) -a $(params.app) /workspace/source/apic/subs.yaml 
      image: 'jtarte/apic-cli:latest'
      name: create-api-subscription
      resources: {}
    - name: sleep-5
      image: ubuntu
      script: | 
        #!/usr/bin/env bash
        sleep 5
    - command: 
        - /workspace/source/apic/test-endpoint.sh
        - https://gw.mycluster-par01-c3c-16x32-bab45e8004bc87ecf7bae04a5ef90ae7-0000.par01.containers.appdomain.cloud/org1/sandbox/cloudfrontend-svc/v1/invoke
        - $(params.app_id)
      image: 'jtarte/apic-cli:latest'
      name: test-api
      resources: {}