apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apic-product
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/tags: cli
    tekton.dev/displayName: "apic product"
spec:
  description: This task performs operations to create a product and upload it. 
  resources:
    inputs :
      - name: source
        type: git
  params:
    - name: pathToContext
      type: string
      default: /workspace/source
    - name: server
      description: The APIC server endpoint
      type: string
    - name: org
      description: the APIC organisation
      type: string
    - name: product 
      description: the name of the product
      type: string
    - name: version
      description: version of the targeted product
      type: string
    - name: swagger
      description: url to the service swagger
      type: string
    - name: service 
      description: naem of service refered by this product
      type: string
    - name: template
      description: name of the product temaplate to use
      type: string
  steps:
    - command:
        - /bin/bash
        - '-c'
        - apic login --accept-license --server $(params.server) --username $USERNAME --password $PASSWORD --realm $REALM
      image: 'jtarte/apic-cli:latest'
      name: login
      resources: {}
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: apic-creds
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: apic-creds
              key: password 
        - name: REALM
          valueFrom:
            secretKeyRef:
              name: apic-creds
              key: realm 
    - name: prepare-product-file
      image: 'ubuntu'
      script: |
        #!/usr/bin/env bash
        cp $(params.pathToContext)/apic/product-templates/$(params.template).yaml product.yaml 
        sed -i 's/#NAME#/$(params.product)/g' product.yaml
        sed -i 's/#VERSION#/$(params.version)/g' product.yaml
        sed -i 's/#SWAGGER#/$(params.swagger)/g' product.yaml
        sed -i 's/#SERVICE#/$(params.service)/g' product.yaml

        cat product.yaml
      resources: {}
    - name: create-product
      command:
        - /bin/bash
        - '-c'
        - apic draft-products:create --server $(params.server) -o $(params.org)  product.yaml
      image: 'jtarte/apic-cli:latest'
      resources: {}