apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apic-api-test
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/tags: cli
    tekton.dev/displayName: "apic api test"
spec:
  description: This task performs operations to test published API. 
  resources:
    inputs :
      - name: source
        type: git
  params:
    - name: server
      description: The APIC server endpoint
      type: string
    - name: org
      description: the APIC organisation
      type: string
    - name: catalog
      description: the targeted APIC catalog
      type: string
    - name: consumer_org
      description: the consumer organisation used for the test
      type: string
    - name: app 
      description: the app used for the test (subscription)
      type: string
    - name: app_id
      description: the api key of the used app.
      type: string
    - name: product 
      description: the name of the product
      type: string
    - name: productVersion
      description: version of the targeted product
      type: string
    - name: gateway
      description: the url of the API gateway
      type: string
    - name: uri
      description: the uri for the test call
      type: string
  steps:
    - command:
        - /bin/bash
        - '-c'
        - apic login --accept-license --server $(params.server) --username $USERNAME --password $PASSWORD --realm $REALM
      image: 'jtarte/apic-cli:latest'
      name: login
      resources: {}
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: apic-creds
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: apic-creds
              key: password 
        - name: REALM
          valueFrom:
            secretKeyRef:
              name: apic-creds
              key: realm 
    - name: prepare-api-subscription
      command:
        - /bin/bash
        - '-c'
        - cat /workspace/source/apic/subs-org.yaml | sed "s#TARGET_PRODUCT#$(apic products:list -s $(params.server) -o $(params.org) -c $(params.catalog) --scope catalog $(params.product) | grep $(param.product):$(param.productVersion) | awk -F ' ' '{print $4}')#g" > /workspace/source/apic/subs.yaml
      image: 'jtarte/apic-cli:latest'
      resources: {}
    - name: create-api-subscription
      command:
        - /bin/bash
        - '-c'
        - apic subscriptions:create --server $(params.server) -o $(params.org) -c $(params.catalog) --consumer-org $(params.consumer_org) -a $(params.app) /workspace/source/apic/subs.yaml 
      image: 'jtarte/apic-cli:latest'
      resources: {}
    - name: sleep-10
      image: ubuntu
      script: | 
        #!/usr/bin/env bash
        sleep 10
    - name: test-api
      command: 
        - /workspace/source/apic/test-endpoint.sh
        - $(params.gateway)/$(params.uri)
        - $(params.app_id)
      image: 'jtarte/apic-cli:latest'
      resources: {}