apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-app
spec:
  resources:
    inputs :
      - name: source
        type: git
      - name: image
        type: image
  params:
    - name: pathToContext
      type: string
      default: /workspace/source
    - name: targetNamespace
      type: string
      default: phonebook
    - name: subdomain
      type: string
    - name: domain
      type: string
    - name: yamlFile
      type: string 
    - name: genericName
      type: string
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;image-registry.openshift-image-registry.svc:5000/default/myservice:latest;$(resources.inputs.image.url);g"
        - "$(params.pathToContext)/$(params.yamlFile)"
    - name: update-yaml2
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;$(params.genericName);$(params.subdomain);g"
        - "$(params.pathToContext)/$(params.yamlFile)"
    - name: update-yaml3
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;192.168.64.2.nip.io;$(params.domain);g"
        - "$(params.pathToContext)/$(params.yamlFile)"
    - name: oc-apply
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash", "-c"]
      args:
        - oc apply -f $(params.pathToContext)/$(params.yamlFile) -n $(params.targetNamespace)