apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: certificate
spec:
  resources:
    inputs:
      - name: source
        type: git
  params:
    - name: pathToContext
      type: string
      default: /workspace/source
    - name: targetNamespace
      type: string
      default: cloud-api
    - name: domain
      type: string
    - name: subdomain
      type: string 
    - name: meshNamespace
      type: string
      default: itsio-system
  steps:
    - name: generate-certificates
      image: centurylink/openssl
      script: |
        #!/usr/bin/env sh
        cd $(inputs.params.pathToContext)/cloud-api
        openssl req -out $(inputs.params.subdomain).$(inputs.params.domain).csr -newkey rsa:2048 -nodes -keyout $(inputs.params.subdomain).$(inputs.params.domain).key -subj "/CN=$(inputs.params.subdomain).$(inputs.params.domain)/O=$(inputs.params.subdomain) subdomain od $(inputs.params.domain) for istio demo"
        openssl x509 -req -days 365 -CA ../ca-cert/$(inputs.params.domain).crt -CAkey ../ca-cert/$(inputs.params.domain).key -set_serial 0 -in $(inputs.params.subdomain).$(inputs.params.domain).csr -out $(inputs.params.subdomain).$(inputs.params.domain).crt
    - name: create-secret
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash", "-c"]
      args: 
      - oc create -n $(inputs.params.meshNamespace) secret tls istio-ingressgateway-$(inputs.params.subdomain)-certs --key $(inputs.params.pathToContext)/cloud-api/$(inputs.params.subdomain).$(inputs.params.domain).key --cert $(inputs.params.pathToContext)/cloud-api/$(inputs.params.subdomain).$(inputs.params.domain).crt
    - name: update-gateway-patch-file
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;-frontend-;-$(inputs.params.subdomain)-;g"
        - "$(inputs.params.pathToContext)/$(inputs.params.subdomain)/gateway-patch.json"
    - name: oc-patch
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash", "-c"]
      args:
        - oc patch -n $(inputs.params.meshNamespace) --type='json' deploy istio-ingressgateway -p "$(cat $(inputs.params.pathToContext)/$(inputs.params.subdomain)/gateway-patch.json)"

