apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: egress
spec:
  resources:
    inputs:
      - name: source
        type: git
  params:
    - name: pathToContext
      type: string
      default: /workspace/source
    - name: targetNamespace
      type: string
      default: phonebook
    - name: host
      type: string
    - name: yamlFile
      type: string 
    - name: oldHost
      type: string
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;$(input.params.oldHost);$(inputs.params.host);g"
        - "$(inputs.params.pathToContext)/$(inputs.params.yamlFile)"
    - name: oc-apply
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash", "-c"]
      args:
        - oc apply -f $(inputs.params.pathToContext)/$(inputs.params.yamlFile) -n $(inputs.params.targetNamespace)