apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: legacy-route
spec:
  resources:
    inputs:
      - name: source
        type: git
  params:
    - name: pathToContext
      type: string
      default: /workspace/source
    - name: targetNamespace
      type: string
    - name: domain
      type: string
    - name: subdomain
      type: string 
    - name: genericName
      type: string
  steps:
    - name: generate-certificates
      image: centurylink/openssl
      script: |
        #!/usr/bin/env sh
        cd $(params.pathToContext)/$(params.genericName)
        openssl req -out $(params.subdomain).$(params.domain).csr -newkey rsa:2048 -nodes -keyout $(params.subdomain).$(params.domain).key -subj "/CN=$(params.subdomain).$(params.domain)/O=$(params.subdomain) subdomain od $(params.domain) for istio demo"
        openssl x509 -req -days 365 -CA ../ca-cert/$(params.domain).crt -CAkey ../ca-cert/$(params.domain).key -set_serial 0 -in $(params.subdomain).$(params.domain).csr -out $(params.subdomain).$(params.domain).crt
    - name: create-route
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash", "-c"]
      args: 
      - oc create route edge --service=service-$(params.subdomain)-a -n $(params.targetNamespace) --hostname=$(params.subdomain).$(params.domain) --key=$(params.pathToContext)/$(params.genericName)/$(params.subdomain).$(params.domain).key --cert=$(params.pathToContext)/$(params.genericName)/$(params.subdomain).$(params.domain).crt --insecure-policy=Redirect


