apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: a-cloud-frontend-mesh-api-upgrade
spec:
  params:
  - name: pathToContext
    value: /workspace/docker-source
  - name: targetNamespace
    value: a-cloud-frontend
  - name: domain
    value: 159.8.94.146.nip.io
  - name: subdomain
    value: cloud-frontend
  - name: genericName
    value: cloud-frontend
  - name: application_script
    value: cloud-frontend/application-api-upgrade.yaml
  - name: virtualservice_script
    value: cloud-frontend/virtual-service-api-upgrade.yaml
  pipelineRef:
    name: internal-service-upgrade
  resources:
  - name: source
    resourceRef:
      name: mesh-apic-demo-git
  - name: image
    resourceRef:
      name: myservice-image