apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: a-cloud-frontend
spec:
  params:
  - name: pathToContext
    value: /workspace/docker-source
  - name: targetNamespace
    value: a-cloud-frontend
  - name: domain
    value: 159.8.94.146.nip.io
  - name: subdomain
    value: cloud-frontend
  - name: genericName
    value: cloud-frontend
  - name: hostBackend
    value: cloud-backend.159.8.94.146.nip.io
  - name: hostLegacy
    value: z-backend.159.8.94.146.nip.io
  pipelineRef:
    name: deploy-frontend
  resources:
  - name: source
    resourceRef:
      name: mesh-apic-demo-git
  - name: image
    resourceRef:
      name: myservice-image