apiVersion: tekton.dev/v1beta1
kind: Pipeline 
metadata:
  name: apic
spec:
  resources:
    - name: source
      type: git
  params:
    - name: server  
    - name: apic_org
    - name: swagger
    - name: product
    - name: catalog
    - name: consumer_org
    - name: app
    - name: app_id
    - name: gateway
    - name: uri
    - name: service
    - name: version
  tasks:
  - name: deploy-api
    taskRef:
      name: apic-cli
    resources:
      inputs:
        - name: source
          resource: source
    params:
    - name: ARGS
      value: "--org $(params.apic_org) /workspace/source/$(params.swagger)"
    - name: verb 
      value: draft-apis:create
    - name: server
      value: $(params.server)
  - name: deploy-product
    taskRef:
      name: apic-cli
    runAfter:
        - deploy-api
    resources:
      inputs:
        - name: source
          resource: source
    params:
    - name: ARGS
      value: "--org $(params.apic_org) /workspace/source/$(params.product)"
    - name: verb 
      value: draft-products:create
    - name: server
      value: $(params.server)
  - name: publish-product
    taskRef:
      name: apic-cli
    runAfter:
        - deploy-product
    resources:
      inputs:
        - name: source
          resource: source
    params:
    - name: ARGS
      value: "--org $(params.apic_org) -c $(params.catalog) /workspace/source/$(params.product)"
    - name: verb 
      value: products:publish
    - name: server
      value: $(params.server)  
  - name: create-test-app
    taskRef:
      name: apic-api-test
    runAfter:
        - publish-product
    resources:
      inputs:
        - name: source
          resource: source
    params:
    - name: server
      value: $(params.server)  
    - name: org
      value: $(params.apic_org) 
    - name: catalog
      value: $(params.catalog) 
    - name: consumer_org
      value: $(params.consumer_org)
    - name: app
      value: $(params.app)
    - name: app_id
      value: $(params.app_id)
    - name: product
      value: $(params.service)-product
    - name: productVersion
      value: $(params.version)
    - name: gateway
      value: $(params.gateway)
    - name: uri
      value: $(params.uri)
    