apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-app
spec:
  inputs:
    resources:
      - name: source
        type: git
      - name: image
        type: image
    params:
      - name: pathToContext
        type: string
        default: /workspace/source
      - name: targetNamespace
        type: string
        default: phonebook
      - name: subdomain
        type: string
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;image-registry.openshift-image-registry.svc:5000/default/myservice:latest;$(inputs.resources.image.url);g"
        - "$(inputs.params.pathToContext)/cloud-api/application.yaml"
    - name: update-yaml2
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;cloud-frontend;$(inputs.params.subdomain);g"
        - "$(inputs.params.pathToContext)/cloud-api/application.yaml"
    - name: oc-apply
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash", "-c"]
      args:
        - oc apply -f $(inputs.params.pathToContext)/cloud-api/application.yaml -n $(inputs.params.targetNamespace)