apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: certs-project
spec:
  resources:
    - name: source
      type: git
  params:
    - name: meshNamespace
      description: the namespace of the service mesh 
      default: istio-system
    - name: targetNamespace
      description: the name of target namespace where the deployment is done
    - name: domain
      description: the domain used for service host (ex.192.168.64.2.nip.io)
    - name: subdomain
      description: the subdomain of the service host (ex cloud-frontend) 
  tasks:
  - name: manage-certificates
    taskRef:
      name: certificate
    resources:
      inputs:
        - name: source
          resource: source
    params:
    - name: targetNamespace
      value: "$(params.targetNamespace)"  
    - name: meshNamespace
      value: "$(params.meshNamespace)"  
    - name: domain
      value: "$(params.domain)" 
    - name: subdomain
      value: "$(params.subdomain)"