apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-project
spec:
  resources:
    - name: source
      type: git
    - name: image
      type: image
  params:
    - name: meshNamespace
      description: the namespace of the service mesh 
      default: istio-system
    - name: targetNamespace
      description: the name of target namespace where the deployment is done
      default: cloud-api
    - name: domain
      description: the name of target namespace where the deployment is done
      default: 192.168.64.2.nip.io
    - name: subdomain
      description: the name of target namespace where the deployment is done
      default: cloud-api  
  tasks:
  - name: deploy-app
    taskRef:
      name: deploy-app
    resources:
      inputs:
        - name: source
          resource: source
        - name: image
          resource: image
    params:
    - name: targetNamespace
      value: "$(params.targetNamespace)"
  - name: deploy-gateway
    taskRef:
      name: deploy-gateway
    resources:
      inputs:
        - name: source
          resource: source
    params:
    - name: targetNamespace
      value: "$(params.targetNamespace)"
    - name: domain
      value: "$(params.domain)"
    - name: subdomain
      value: "$(params.subdomain)"