apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test2
spec: 
  serviceAccountName: pipeline
  taskRef:
    name: apic-api-test
  resources:
    inputs:
    - name: source
      resourceRef:
        name: mesh-apic-demo-git
  params:
  - name: server
    value: api.mycluster-par01-c3c-16x32-bab45e8004bc87ecf7bae04a5ef90ae7-0000.par01.containers.appdomain.cloud
  - name: org
    value: org1
  - name: catalog
    value: sandbox
  - name: consumer_org
    value: jerome-tarte 
  - name: app
    value: test-app
  - name: app_id
    value: b349b23c1ccc34e9903bb4d178bd34b8