apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-virtualservice
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: pathToContext
        type: string
        default: /workspace/source
      - name: targetNamespace
        type: string
        default: cloud-api
      - name: subdomain
        type: string
        default: cloud-api
      - name: domain
        type: string
        default: cloud-api
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;frontend;$(inputs.params.subdomain);g"
        - "$(inputs.params.pathToContext)/cloud-api/virtual-service.yaml"
    - name: update-yaml-2
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;192.168.64.2.nip.io;$(inputs.params.domain);g"
        - "$(inputs.params.pathToContext)/cloud-api/virtual-service.yaml"
    - name: oc-apply
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash", "-c"]
      args:
        - oc apply -f $(inputs.params.pathToContext)/cloud-api/virtual-service.yaml -n $(inputs.params.targetNamespace)