swagger: '2.0'
info:
  title: CloudFrontEnd-Svc
  version: 1.0.1
  description: Expose the cloud frontend service managed by service mesh
schemes:
  - https
basePath: /cloudfrontend-svc/v1
produces:
  - application/json
consumes:
  - application/json
security:
  - clientID: []
definitions:
  InvokeResponse:
    type: object
    additionalProperties: false
    properties:
      stack:
        type: string
        example: '[service-cloud-backend-a v1 calls [service-cloud-backend-b v1 ] ]'
paths:
  /invoke:
    get:
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/InvokeResponse'
        '401':
          description: unauthorized
          schema:
            type: object
      consumes:
        - application/json
      produces:
        - application/json
    parameters:
      - name: mode
        in: header
        required: false
        description: provide information about service level (gold)
        type: string
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  properties:
    target-url:
      value: 'https://cloud-frontend.159.8.94.146.nip.io'
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
  catalogs:
    sandbox:
      properties:
        target-url: 'https://cloud-frontend.159.8.94.146.nip.io'
    integration:
      properties:
        target-url: 'https://cloud-frontend.159.8.94.146.nip.io'
